name: PyBand Workflow
on: [push, pull_request]

jobs:
  pyband-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        shell: bash
        run: |
          python -m pip install poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install pytest
        shell: bash
        run: pip install pytest==7.1.3

      - name: Configure poetry
        shell: bash
        run: |
          poetry env use system
          poetry config virtualenvs.create false
          poetry env info

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Test with pytest
        working-directory: ${{env.working-directory}}
        run: |
          pytest
